spring.application.name=SpringBootCURD

spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.url=jdbc:h2:file:D:/data/demo
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect


spring.h2.console.enabled=true
#spring.jpa.defer-datasource-initialization=true

spring.h2.console.path=/h2-console
spring.h2.console.settings.trace=false
spring.h2.console.settings.web-allow-others=false

# set the custom port number
#server.port:8091

# Disable the default application server
#spring.main.web-application-type=none

#spring.security.user.name=asn
#spring.security.user.password=asn